/**
 * INT4 DEQUANT MATMUL — generator for the whole int4_matmul family.
 *
 * Replaces 9 hand-maintained .wgsl files that differed on exactly four knobs:
 *   outF32     f16 vs f32 output (one cast at the write — LM head wants f32)
 *   rowsPerWG  1 / 4 / 8 output rows per workgroup (input-bandwidth tiling)
 *   subgroups  subgroupAdd (32 threads) vs tree reduction (64 threads)
 *   m          1 (GEMV decode) or 4 (batched GEMM for spec-decode/prefill)
 *
 * Everything else — bindings, PODArgs, dequant math — is identical, so the
 * shaders stay auditable: the emitted WGSL is plain readable text, and
 * `debugDumpAll()` prints every shipped variant. To read one from a shell:
 *
 *   node -e "import('./src/compiler/shaders/int4_matmul.gen.ts')
 *              .then(m => console.log(m.debugDumpAll()))"
 *
 * Math: output[row] = dot(input, dequant(weights[row])) with
 * dequant(nibble) = (nibble - 7) * scale. The per-group scale is factored out
 * of the 8 unpacked terms — s * (Σ xᵢ·(nᵢ-7)) — one multiply per u32 word
 * instead of eight, and slightly more accurate. Accumulation is f32
 * (fixes TVM's f16 precision loss). Dimensions arrive via PODArgs uniforms,
 * so the same shader serves K=3072 and K=8192; no model-shape literals here.
 *
 * Bindings (match the old int4_matmul.wgsl 1:1 so bind groups are reused):
 *   @binding(0) output   array<f16|f32> read_write
 *   @binding(1) input    array<f16>     read
 *   @binding(2) scales   array<f16>     read
 *   @binding(3) weights  array<u32>     read
 *   @binding(4) podArgs  uniform {K_PACKED, SCALES_PER_ROW, packGridDimX}
 */

export interface Int4MatmulOpts {
  /** f32 output (LM head logits) instead of f16. */
  outF32?: boolean
  /** Output rows per workgroup: 1, 4 or 8. >1 requires subgroups. */
  rowsPerWG?: 1 | 4 | 8
  /** Use subgroupAdd (32-thread WG) instead of a 64-thread tree reduction. */
  subgroups?: boolean
  /** Batched input rows: 1 (GEMV) or 4 (M=4 GEMM). m=4 requires subgroups. */
  m?: 1 | 4
}

/** Entry-point name for a variant (same names the old .wgsl files used). */
export function int4MatmulEntry(opts: Int4MatmulOpts = {}): string {
  const { outF32 = false, rowsPerWG = 1, subgroups = false, m = 1 } = opts
  if (m === 4) return 'int4_matmul_batched_m4'
  let name = 'int4_matmul'
  if (outF32) name += '_f32'
  if (rowsPerWG === 4) name += '_tiled'
  else if (rowsPerWG === 8) name += '_tiled8'
  else if (subgroups) name += '_sg'
  return name
}

// Σ xᵢ·(nibble(p, i) - 7), scale factored out by the caller.
function dequantDot(p: string, x: (i: number) => string, indent: string): string {
  const terms: string[] = []
  for (let i = 0; i < 8; i++) {
    const shift = String(i * 4).padStart(2)
    terms.push(`${x(i)} * (f32((${p} >> ${shift}u) & 15u) - 7.0)`)
  }
  const pairs: string[] = []
  for (let i = 0; i < 8; i += 2) pairs.push(`${terms[i]} + ${terms[i + 1]}`)
  return pairs.join(`\n${indent}+ `)
}

/** Render the WGSL for one variant. */
export function int4MatmulWGSL(opts: Int4MatmulOpts = {}): string {
  const { outF32 = false, rowsPerWG = 1, subgroups = false, m = 1 } = opts
  if (rowsPerWG !== 1 && !subgroups) throw new Error('rowsPerWG > 1 requires subgroups')
  if (m === 4 && (!subgroups || rowsPerWG !== 4)) throw new Error('m=4 requires subgroups + rowsPerWG=4')

  const entry = int4MatmulEntry(opts)
  const outType = outF32 ? 'f32' : 'f16'
  const wgSize = subgroups ? 32 : 64
  const cast = (v: string) => (outF32 ? v : `f16(${v})`)
  const rows = [...Array(rowsPerWG).keys()]
  const batches = [...Array(m).keys()]

  const header = `// GENERATED by src/compiler/shaders/int4_matmul.gen.ts — do not edit by hand.
// Variant: ${entry} (out=${outType}, rowsPerWG=${rowsPerWG}, ${subgroups ? 'subgroupAdd' : 'tree reduction'}${m > 1 ? `, M=${m}` : ''})
${subgroups ? '// Requires subgroup size 32 (gated in chat.ts via a shader probe).\n' : ''}
enable f16;
${subgroups ? 'enable subgroups;\n' : ''}
@group(0) @binding(0) var<storage, read_write> output_buf : array<${outType}>;
@group(0) @binding(1) var<storage, read> input_buf : array<f16>;
@group(0) @binding(2) var<storage, read> scales : array<f16>;
@group(0) @binding(3) var<storage, read> weights : array<u32>;

struct PODArgs {
  K_PACKED: u32,        // K / 8  (u32 words per weight row)
  SCALES_PER_ROW: u32,  // K / 32 (int4 group scales per weight row)
  packGridDimX: u32     // N (number of output ${m > 1 ? 'columns' : 'elements'})
}
@group(0) @binding(4) var<uniform> podArgs : PODArgs;
`

  const prologue = `
@compute @workgroup_size(${wgSize}, 1, 1)
fn ${entry}(
  @builtin(workgroup_id) blockIdx : vec3<u32>,
  @builtin(num_workgroups) gridDim : vec3<u32>,
  @builtin(local_invocation_id) threadIdx : vec3<u32>
) {
  let row_base : u32 = (blockIdx.z * gridDim.x + blockIdx.x) * ${rowsPerWG}u;
  if (row_base >= podArgs.packGridDimX) { return; }

  let K_PACKED : u32 = podArgs.K_PACKED;
  let SCALES_PER_ROW : u32 = podArgs.SCALES_PER_ROW;
  let tid : u32 = threadIdx.x;
`

  // Per-thread K-chunk loop. Each thread strides by the workgroup width.
  const rowDecl = rows.map((r) => `  let r${r} = row_base${r ? ` + ${r}u` : ''};`).join('\n')

  let body: string
  if (m === 1) {
    const accDecl = rows.map((r) => `  var acc${r} : f32 = 0.0;`).join('\n')
    const loads =
      rowsPerWG === 1
        ? [...Array(8).keys()]
            .map((i) => `    let i${i} = f32(input_buf[base${i ? ` + ${i}u` : ''}]);`)
            .join('\n')
        : `    // Load 8 inputs once, reuse across all ${rowsPerWG} rows.\n` +
          [...Array(8).keys()]
            .map((i) => `    let i${i} = f32(input_buf[base${i ? ` + ${i}u` : ''}]);`)
            .join('\n')
    const rowBlocks = rows
      .map(
        (r) => `    { // row r${r}: one (packed, scale) load, scale factored out of the 8 terms
      let p = weights[r${r} * K_PACKED + w_offset];
      let s = f32(scales[r${r} * SCALES_PER_ROW + sc_idx]);
      acc${r} = acc${r} + s * (
          ${dequantDot('p', (i) => `i${i}`, '        ')});
    }`,
      )
      .join('\n')
    body = `
${accDecl}

${rowDecl}

  for (var chunk : u32 = 0u; chunk < K_PACKED / ${wgSize}u; chunk = chunk + 1u) {
    let w_offset : u32 = tid + chunk * ${wgSize}u;
    let base : u32 = w_offset * 8u;
    let sc_idx : u32 = w_offset >> 2u;

${loads}

${rowBlocks}
  }
`
  } else {
    // M=4: load the 8 inputs of every batch row, dequantize each weight row
    // once (nibbles only — the scale multiplies the batch-row dot), and
    // accumulate m × rowsPerWG cells.
    const accDecl = batches
      .map((b) => '  ' + rows.map((r) => `var a${b}${r} : f32 = 0.0;`).join(' '))
      .join('\n')
    const loads = batches
      .map((b) =>
        [...Array(8).keys()]
          .map((i) => `    let b${b}_${i} = f32(input_buf[${b}u * K + base${i ? ` + ${i}u` : ''}]);`)
          .join('\n'),
      )
      .join('\n')
    const rowBlocks = rows
      .map((r) => {
        const nibbles = [...Array(8).keys()]
          .map((i) => `      let n${i} = f32((p >> ${String(i * 4).padStart(2)}u) & 15u) - 7.0;`)
          .join('\n')
        const accs = batches
          .map(
            (b) =>
              `      a${b}${r} = a${b}${r} + s * (b${b}_0*n0 + b${b}_1*n1 + b${b}_2*n2 + b${b}_3*n3 + b${b}_4*n4 + b${b}_5*n5 + b${b}_6*n6 + b${b}_7*n7);`,
          )
          .join('\n')
        return `    { // weight row r${r}: unpack nibbles once, reuse across all ${m} batch rows
      let p = weights[r${r} * K_PACKED + w_offset];
      let s = f32(scales[r${r} * SCALES_PER_ROW + sc_idx]);
${nibbles}
${accs}
    }`
      })
      .join('\n')
    body = `
  let K : u32 = K_PACKED * 8u;  // elements per input row

${accDecl}

${rowDecl}

  for (var chunk : u32 = 0u; chunk < K_PACKED / ${wgSize}u; chunk = chunk + 1u) {
    let w_offset : u32 = tid + chunk * ${wgSize}u;
    let base : u32 = w_offset * 8u;
    let sc_idx : u32 = w_offset >> 2u;

${loads}

${rowBlocks}
  }
`
  }

  let tail: string
  if (subgroups) {
    const sums =
      m === 1
        ? rows.map((r) => `  let sum${r} = subgroupAdd(acc${r});`).join('\n')
        : batches
            .map((b) => '  ' + rows.map((r) => `let s${b}${r} = subgroupAdd(a${b}${r});`).join(' '))
            .join('\n')
    const writes =
      m === 1
        ? rows.map((r) => `    output_buf[r${r}] = ${cast(`sum${r}`)};`).join('\n')
        : `    let N = podArgs.packGridDimX;\n` +
          batches
            .map((b) =>
              rows.map((r) => `    output_buf[${b}u * N + r${r}] = ${cast(`s${b}${r}`)};`).join('\n'),
            )
            .join('\n')
    tail = `
  // Uniform subgroup sums (all 32 lanes always present and active).
${sums}

  if (tid == 0u) {
${writes}
  }
}
`
  } else {
    tail = `
  // Tree reduction in f32 across the 64 threads.
  red_buf[tid] = acc0;
  workgroupBarrier();
  if (tid < 32u) { red_buf[tid] = red_buf[tid] + red_buf[tid + 32u]; }
  workgroupBarrier();
  if (tid < 16u) { red_buf[tid] = red_buf[tid] + red_buf[tid + 16u]; }
  workgroupBarrier();
  if (tid < 8u) { red_buf[tid] = red_buf[tid] + red_buf[tid + 8u]; }
  workgroupBarrier();
  if (tid < 4u) { red_buf[tid] = red_buf[tid] + red_buf[tid + 4u]; }
  workgroupBarrier();
  if (tid < 2u) { red_buf[tid] = red_buf[tid] + red_buf[tid + 2u]; }
  workgroupBarrier();
  if (tid < 1u) { red_buf[tid] = red_buf[tid] + red_buf[tid + 1u]; }
  workgroupBarrier();

  if (tid == 0u) {
    output_buf[r0] = ${cast('red_buf[0]')};
  }
}
`
  }

  const sharedMem = subgroups ? '' : '\nvar<workgroup> red_buf : array<f32, 64>;\n'
  return header + sharedMem + prologue + body + tail
}

/** The 9 shipped variants (1:1 with the deleted .wgsl files). */
export const INT4_MATMUL_VARIANTS: ReadonlyArray<Int4MatmulOpts> = [
  {},                                            // int4_matmul
  { subgroups: true },                           // int4_matmul_sg
  { subgroups: true, rowsPerWG: 4 },             // int4_matmul_tiled
  { subgroups: true, rowsPerWG: 8 },             // int4_matmul_tiled8
  { outF32: true },                              // int4_matmul_f32
  { outF32: true, subgroups: true },             // int4_matmul_f32_sg
  { outF32: true, subgroups: true, rowsPerWG: 4 }, // int4_matmul_f32_tiled
  { outF32: true, subgroups: true, rowsPerWG: 8 }, // int4_matmul_f32_tiled8
  { subgroups: true, rowsPerWG: 4, m: 4 },       // int4_matmul_batched_m4
]

/** Human-auditable dump of every shipped variant. */
export function debugDumpAll(): string {
  return INT4_MATMUL_VARIANTS.map(
    (v) => `// ${'═'.repeat(70)}\n// ${int4MatmulEntry(v)}\n// ${'═'.repeat(70)}\n${int4MatmulWGSL(v)}`,
  ).join('\n')
}
