/**
 * TOKENIZER-BPE UNIT TESTS — pins the hand-rolled byte-level BPE in
 * src/zero-tvm/tokenizer-bpe.ts (Qwen3) against the HuggingFace reference
 * implementation.
 *
 * Fully offline: fixtures-qwen3.json ({text, ids, decoded}) was generated by
 * scripts/gen-tokenizer-fixtures-qwen.mjs with @huggingface/transformers
 * loading the exact tokenizer the app ships (mlc-ai/Qwen3-4B-q4f16_1-MLC),
 * and tokenizer-qwen3.json here is a committed (minified, field-complete)
 * copy of that same file, so the test builds the app tokenizer from the
 * app's own vocab/merges.
 *
 * Regenerate fixtures (needs network): npm run gen:tokenizer-fixtures-qwen
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { describe, expect, test } from 'vitest'

import {
  buildChatPrompt,
  createByteLevelTokenizer,
  QWEN3_DEFAULT_SYSTEM_MESSAGE,
} from '../../src/zero-tvm/tokenizer-bpe.js'
import type { ByteLevelTokenizerJSON } from '../../src/zero-tvm/tokenizer-bpe.js'

const HERE = dirname(fileURLToPath(import.meta.url))

interface Fixture {
  text: string
  ids: number[]
  decoded: string
}

const fixtures: Fixture[] = JSON.parse(readFileSync(resolve(HERE, 'fixtures-qwen3.json'), 'utf8'))
const tokenizerJson: ByteLevelTokenizerJSON = JSON.parse(
  readFileSync(resolve(HERE, 'tokenizer-qwen3.json'), 'utf8'),
)
const tok = createByteLevelTokenizer(tokenizerJson)

// ---------------------------------------------------------------------------
// Known decode divergences from the HF reference: NONE. Unlike Phi-3 (where
// the app deliberately strips the special:false </s> that HF keeps), Qwen3's
// decode semantics match HF skip_special_tokens exactly — special:true added
// tokens are stripped, special:false ones (<think>, <tool_call>, ...) render
// literally in both implementations.
// ---------------------------------------------------------------------------

const label = (text: string) =>
  JSON.stringify(text.length > 48 ? text.slice(0, 48) + '…' : text)

describe('encode() matches the HuggingFace reference', () => {
  for (const { text, ids } of fixtures) {
    test(label(text), () => {
      expect(tok.encode(text)).toEqual(ids)
    })
  }
})

describe('decode() matches the HuggingFace reference', () => {
  for (const { text, ids, decoded } of fixtures) {
    test(label(text), () => {
      expect(tok.decode(ids)).toBe(decoded)
    })
  }
})

describe('encode/decode round-trip', () => {
  // decode(encode(text)) must reproduce the reference's decoded form (which
  // equals `text` for anything without special tokens; NFC normalization and
  // special-token stripping are the only lossy steps).
  for (const { text, decoded } of fixtures) {
    test(label(text), () => {
      expect(tok.decode(tok.encode(text))).toBe(decoded)
    })
  }
})

describe('buildChatPrompt', () => {
  test('system+user template matches the reference fixture ids', () => {
    // Same messages the fixture-generation script used — and the script
    // itself verified the raw string against tokenizer.apply_chat_template.
    const fixture = fixtures.find((f) =>
      f.text.startsWith('<|im_start|>system\nYou are a helpful'),
    )
    expect(fixture).toBeDefined()
    const ids = buildChatPrompt(
      [
        { role: 'system', content: QWEN3_DEFAULT_SYSTEM_MESSAGE },
        { role: 'user', content: 'What is the capital of France?' },
      ],
      tok,
    )
    expect(ids).toEqual(fixture!.ids)
  })

  test('multi-turn template matches the reference fixture ids', () => {
    const fixture = fixtures.find((f) => f.text.includes('Write a haiku'))
    expect(fixture).toBeDefined()
    const ids = buildChatPrompt(
      [
        { role: 'user', content: 'Write a haiku about GPUs.' },
        { role: 'assistant', content: 'Warm silicon hums' },
        { role: 'user', content: 'Continue it' },
      ],
      tok,
    )
    expect(ids).toEqual(fixture!.ids)
  })

  test('thinking: false appends the empty <think> block from the template', () => {
    // The chat_template's `enable_thinking is false` branch — verified
    // against apply_chat_template(..., enable_thinking: false) at fixture
    // generation time.
    const fixture = fixtures.find((f) => f.text.endsWith('<think>\n\n</think>\n\n'))
    expect(fixture).toBeDefined()
    const ids = buildChatPrompt(
      [
        { role: 'system', content: QWEN3_DEFAULT_SYSTEM_MESSAGE },
        { role: 'user', content: 'What is the capital of France?' },
      ],
      tok,
      { thinking: false },
    )
    expect(ids).toEqual(fixture!.ids)
  })

  test('default (thinking) prompt ends with the bare generation prompt', () => {
    const ids = buildChatPrompt([{ role: 'user', content: 'hi' }], tok)
    // ... <|im_start|> "assistant" "\n" — and nothing after.
    const tail = tok.decode(ids.slice(-3))
    expect(tail).toBe('assistant\n')
    expect(ids[ids.length - 3]).toBe(151644) // <|im_start|> (stripped by decode)
  })
})

describe('tokenizer basics', () => {
  test('eos/bos/stop ids match mlc-chat-config', () => {
    expect(tok.eosId).toBe(151645) // <|im_end|>
    expect(tok.bosId).toBe(151643) // <|endoftext|> (Qwen3 has no real BOS)
    expect(tok.stopIds).toEqual([151645, 151643])
  })

  test('special tokens encode to single ids', () => {
    expect(tok.encode('<|endoftext|>')).toEqual([151643])
    expect(tok.encode('<|im_start|>')).toEqual([151644])
    expect(tok.encode('<|im_end|>')).toEqual([151645])
    // Non-special added tokens are extracted too...
    expect(tok.encode('<think>')).toEqual([151667])
    expect(tok.encode('</think>')).toEqual([151668])
    // ...and survive decode (special:false), unlike the special ones.
    expect(tok.decode([151667])).toBe('<think>')
    expect(tok.decode([151645])).toBe('')
  })
})

describe('pre-tokenizer regex regressions', () => {
  test('\\p{N} splits every digit into its own token', () => {
    // Qwen3 splits digits singly (not in runs of ≤3 like Llama-3).
    expect(tok.encode('1234567890')).toHaveLength(10)
    expect(tok.encode('42')).toHaveLength(2)
  })

  test('contraction branch is case-insensitive', () => {
    // (?i:'s|'t|...) — "'T" must split off exactly like "'t". BPE is
    // context-free per pre-token piece, so a correct split means
    // encode(word + contraction) === encode(word) ++ encode(contraction).
    expect(tok.encode("don't")).toEqual([...tok.encode('don'), ...tok.encode("'t")])
    expect(tok.encode("DON'T")).toEqual([...tok.encode('DON'), ...tok.encode("'T")])
    expect(tok.decode(tok.encode("DON'T"))).toBe("DON'T")
  })

  test('trailing whitespace takes the \\s+(?!\\S) branch, not word-prefix spaces', () => {
    // "a b" keeps the space glued to "b" (Ġb); trailing spaces stand alone.
    expect(tok.decode(tok.encode('a b  '))).toBe('a b  ')
    expect(tok.decode(tok.encode('   '))).toBe('   ')
  })

  test('newline runs glue onto preceding whitespace (\\s*[\\r\\n]+)', () => {
    expect(tok.decode(tok.encode('x  \n\ny'))).toBe('x  \n\ny')
    expect(tok.decode(tok.encode('crlf\r\nline'))).toBe('crlf\r\nline')
  })

  test('punctuation takes an optional leading space and trailing newlines', () => {
    // " ?[^\s\p{L}\p{N}]+[\r\n]*"
    expect(tok.decode(tok.encode('end.\nnext'))).toBe('end.\nnext')
    expect(tok.decode(tok.encode('a ... b'))).toBe('a ... b')
  })
})

describe('byte-level coverage', () => {
  test('every single byte 0x00-0xFF round-trips through encode/decode', () => {
    // No byte-fallback tokens and no <unk> — the 256 byte-alphabet chars are
    // ordinary vocab entries, so any byte sequence must round-trip exactly.
    for (let b = 0; b < 256; b++) {
      const ch = String.fromCharCode(b)
      expect(tok.decode(tok.encode(ch))).toBe(ch)
    }
  })

  test('NFC normalizer folds decomposed accents at encode time', () => {
    // "é" as e + U+0301 must encode identically to precomposed U+00E9 —
    // decode then returns the NFC form.
    const decomposed = 'cafe\u0301'
    const composed = 'caf\u00E9'
    expect(tok.encode(decomposed)).toEqual(tok.encode(composed))
    expect(tok.decode(tok.encode(decomposed))).toBe(composed)
  })

  test('multi-codepoint emoji round-trip (bytes span multiple tokens)', () => {
    const zwj = '👨‍👩‍👧‍👦'
    expect(tok.decode(tok.encode(zwj))).toBe(zwj)
  })
})
