/**
 * TOKENIZER-BPE FAMILY TESTS — pins the hand-rolled byte-level BPE in
 * src/zero-tvm/tokenizer-bpe.ts on the Qwen3.5 and Qwen3.8 vocabs, against
 * the HuggingFace reference implementation.
 *
 * Same contract as tokenizer-bpe.test.ts (Qwen3), parameterized by tag:
 * fixtures-<tag>.json ({text, ids, decoded}) was generated by
 * scripts/gen-tokenizer-fixtures-bpe.mjs with @huggingface/transformers
 * loading the exact tokenizer the app ships, and tokenizer-<tag>.json is a
 * committed (minified, field-complete) copy of that same file.
 *
 *   qwen35  mlc-ai/Qwen3.5-4B-q4f16_1-MLC, generation 'qwen35'
 *   qwen38  mlx-community/Qwen3.8-27B-4bit, generation 'qwen38'
 *
 * Qwen3.5 and Qwen3.8 share the vocab SIZE (248044) but not the merges, so
 * one fixture set cannot cover both — verified while generating (the
 * vocabularies compare equal, the merge lists do not).
 *
 * Regenerate fixtures (needs network for the reference side):
 *   node scripts/gen-tokenizer-fixtures-bpe.mjs --tag qwen35 \
 *     --repo mlc-ai/Qwen3.5-4B-q4f16_1-MLC --generation qwen35 \
 *     --local-json .weights-local/Qwen3.5-4B-q4f16_1-MLC/tokenizer.json
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { describe, expect, test } from 'vitest'

import {
  buildChatPrompt,
  createByteLevelTokenizer,
  QWEN38_REASONING_INSTRUCTIONS,
} from '../../src/zero-tvm/tokenizer-bpe.js'
import type { ByteLevelTokenizerJSON } from '../../src/zero-tvm/tokenizer-bpe.js'

const HERE = dirname(fileURLToPath(import.meta.url))

interface Fixture {
  text: string
  ids: number[]
  decoded: string
}

type ChatMsg = { role: 'system' | 'user' | 'assistant'; content: string }

// Checkpoint facts: added-token ids appended after the 248044-entry BPE
// vocab. Hardcoded (not read from the file) so generating fixtures from the
// WRONG checkpoint fails here instead of pinning the wrong vocab.
const ADDED = { endoftext: 248044, imStart: 248045, imEnd: 248046 } as const

const TAGS = [
  { tag: 'qwen35', generation: 'qwen35' },
  { tag: 'qwen38', generation: 'qwen38' },
] as const

const label = (text: string) =>
  JSON.stringify(text.length > 48 ? text.slice(0, 48) + '…' : text)

for (const { tag, generation } of TAGS) {
  const fixtures: Fixture[] = JSON.parse(
    readFileSync(resolve(HERE, `fixtures-${tag}.json`), 'utf8'),
  )
  const tokenizerJson: ByteLevelTokenizerJSON = JSON.parse(
    readFileSync(resolve(HERE, `tokenizer-${tag}.json`), 'utf8'),
  )
  const tok = createByteLevelTokenizer(tokenizerJson)

  describe(`[${tag}] encode() matches the HuggingFace reference`, () => {
    for (const { text, ids } of fixtures) {
      test(label(text), () => {
        expect(tok.encode(text)).toEqual(ids)
      })
    }
  })

  describe(`[${tag}] decode() matches the HuggingFace reference`, () => {
    for (const { text, ids, decoded } of fixtures) {
      test(label(text), () => {
        expect(tok.decode(ids)).toBe(decoded)
      })
    }
  })

  describe(`[${tag}] encode/decode round-trip`, () => {
    for (const { text, decoded } of fixtures) {
      test(label(text), () => {
        expect(tok.decode(tok.encode(text))).toBe(decoded)
      })
    }
  })

  describe(`[${tag}] template ids match the reference fixtures`, () => {
    const by = (pred: (f: Fixture) => boolean): Fixture => {
      const fixture = fixtures.find(pred)
      expect(fixture, 'generator must emit this shape').toBeDefined()
      return fixture!
    }
    const chat = (messages: ChatMsg[], opts?: { thinking?: boolean }) =>
      buildChatPrompt(messages, tok, { ...opts, generation })

    test('system+user turn', () => {
      const sys: ChatMsg[] = [
        { role: 'system', content: 'You are a helpful assistant.' },
        { role: 'user', content: 'What is the capital of France?' },
      ]
      // qwen38 thinking prepends the reasoning preamble, so its fixture text
      // opens with the instructions rather than the system content.
      const fixture = generation === 'qwen38'
        ? by((f) => f.text.startsWith('<|im_start|>system\nReasoning effort'))
        : by((f) => f.text.startsWith('<|im_start|>system\nYou are a helpful'))
      expect(chat(sys)).toEqual(fixture.ids)
    })

    test('multi-turn', () => {
      const fixture = by((f) => f.text.includes('Write a haiku'))
      expect(chat([
        { role: 'user', content: 'Write a haiku about GPUs.' },
        { role: 'assistant', content: 'Warm silicon hums' },
        { role: 'user', content: 'Continue it' },
      ])).toEqual(fixture.ids)
    })

    test('past assistant turn carrying a </think> block', () => {
      // qwen35 splits reasoning back out, qwen38 keeps the turn whole —
      // the same messages must encode DIFFERENTLY per generation.
      const fixture = by((f) => f.text.includes('Think step by step'))
      expect(chat([
        { role: 'user', content: 'Think step by step.' },
        { role: 'assistant', content: '<think>\nfirst principles\n</think>\n\nParis.' },
        { role: 'user', content: 'And Spain?' },
      ])).toEqual(fixture.ids)
    })

    test('non-thinking appends the empty <think> block', () => {
      const fixture = by((f) => f.text.endsWith('<think>\n\n</think>\n\n'))
      expect(chat(
        [
          { role: 'system', content: 'You are a helpful assistant.' },
          { role: 'user', content: 'What is the capital of France?' },
        ],
        { thinking: false },
      )).toEqual(fixture.ids)
    })

    test('thinking generation prompt opens <think>', () => {
      const ids = chat([{ role: 'user', content: 'hi' }])
      const imStart = tok.encode('<|im_start|>')
      expect(imStart).toEqual([ADDED.imStart])
      const tail = [
        ...tok.encode('<|im_start|>assistant\n'),
        ...tok.encode('<think>\n'),
      ]
      expect(ids.slice(-tail.length)).toEqual(tail)
    })
  })

  describe(`[${tag}] tokenizer basics`, () => {
    test('eos/bos/stop ids are the appended added tokens', () => {
      expect(tok.eosId).toBe(ADDED.imEnd)
      expect(tok.bosId).toBe(ADDED.endoftext)
      expect(tok.stopIds).toEqual([ADDED.imEnd, ADDED.endoftext])
    })

    test('special tokens encode to single ids', () => {
      expect(tok.encode('<|endoftext|>')).toEqual([ADDED.endoftext])
      expect(tok.encode('<|im_start|>')).toEqual([ADDED.imStart])
      expect(tok.encode('<|im_end|>')).toEqual([ADDED.imEnd])
      expect(tok.decode([ADDED.imEnd])).toBe('')
    })
  })

  describe(`[${tag}] byte-level coverage`, () => {
    test('every single byte 0x00-0xFF round-trips through encode/decode', () => {
      for (let b = 0; b < 256; b++) {
        const ch = String.fromCharCode(b)
        expect(tok.decode(tok.encode(ch))).toBe(ch)
      }
    })

    test('NFC normalizer folds decomposed accents at encode time', () => {
      const decomposed = 'café'
      const composed = 'café'
      expect(tok.encode(decomposed)).toEqual(tok.encode(composed))
      expect(tok.decode(tok.encode(decomposed))).toBe(composed)
    })
  })

  describe(`[${tag}] generation-prompt split is token-identical to one encode`, () => {
    // Same structural argument as tokenizer-bpe.test.ts: the generation
    // prompt opens with the added token <|im_start|>, so no merge crosses
    // the history/generation boundary. Re-proven here because the qwen35/38
    // generation prompts are LONGER (trailing <think>\n) than qwen3's.
    const messages: ChatMsg[] = [
      { role: 'user', content: 'q1' },
      { role: 'assistant', content: 'a1' },
      { role: 'user', content: 'q2' },
    ]
    for (const thinking of [false, true]) {
      test(`thinking=${thinking}`, () => {
        const split = { genStart: -1 }
        const ids = buildChatPrompt(messages, tok, {
          ...(thinking ? {} : { thinking: false }),
          generation,
          split,
        })
        expect(split.genStart).toBeGreaterThan(0)
        expect(ids[split.genStart]).toBe(ADDED.imStart)
        const tail = buildChatPrompt(messages, tok, {
          ...(thinking ? {} : { thinking: false }),
          generation,
        })
        expect(ids).toEqual(tail)
        // And the tail from the boundary is exactly the generation prompt.
        const genText = thinking
          ? '<|im_start|>assistant\n<think>\n'
          : '<|im_start|>assistant\n<think>\n\n</think>\n\n'
        expect(ids.slice(split.genStart)).toEqual(tok.encode(genText))
      })
    }
  })
}

describe('[qwen38] reasoning instructions', () => {
  const tok = createByteLevelTokenizer(JSON.parse(
    readFileSync(resolve(HERE, 'tokenizer-qwen38.json'), 'utf8'),
  ) as ByteLevelTokenizerJSON)

  test('thinking system turn carries the preamble verbatim', () => {
    const ids = buildChatPrompt(
      [
        { role: 'system', content: 'You are helpful.' },
        { role: 'user', content: 'Hi' },
      ],
      tok,
      { generation: 'qwen38' },
    )
    const head = '<|im_start|>system\n' + QWEN38_REASONING_INSTRUCTIONS + '\n\nYou are helpful.<|im_end|>\n'
    expect(ids.slice(0, tok.encode(head).length)).toEqual(tok.encode(head))
  })

  test('thinking user-first conversation synthesizes the system turn', () => {
    const ids = buildChatPrompt([{ role: 'user', content: 'Hi' }], tok, { generation: 'qwen38' })
    const head = '<|im_start|>system\n' + QWEN38_REASONING_INSTRUCTIONS + '<|im_end|>\n'
    expect(ids.slice(0, tok.encode(head).length)).toEqual(tok.encode(head))
  })

  test('non-thinking emits no instructions', () => {
    const ids = buildChatPrompt(
      [
        { role: 'system', content: 'You are helpful.' },
        { role: 'user', content: 'Hi' },
      ],
      tok,
      { generation: 'qwen38', thinking: false },
    )
    expect(tok.decode(ids)).not.toContain('Reasoning effort')
  })
})
