/**
 * TOKENIZER UNIT TESTS — pins the hand-rolled BPE in src/zero-tvm/tokenizer.ts
 * against the HuggingFace reference implementation.
 *
 * Fully offline: fixtures.json ({text, ids, decoded}) was generated by
 * scripts/gen-tokenizer-fixtures.mjs with @huggingface/transformers loading
 * the exact tokenizer the app ships (mlc-ai/Phi-3-mini-4k-instruct-q4f16_1-MLC),
 * and tokenizer.json here is a committed copy of that same file, so the test
 * builds the app tokenizer from the app's own vocab/merges.
 *
 * Regenerate fixtures (needs network): npm run gen:tokenizer-fixtures
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { describe, expect, test, vi } from 'vitest'

// tokenizer.ts imports PHI3_MODEL_BASE from weight-loader.ts, whose module
// top level touches browser-only globals (GPUBufferUsage). The tokenizer
// itself never uses them in Node, so stub the one constant it needs.
vi.mock('../../src/zero-tvm/weight-loader.js', () => ({
  PHI3_MODEL_BASE:
    'https://huggingface.co/mlc-ai/Phi-3-mini-4k-instruct-q4f16_1-MLC/resolve/main/',
}))

const { buildChatPrompt, createTokenizer } = await import('../../src/zero-tvm/tokenizer.js')
type TokenizerJSON = import('../../src/zero-tvm/tokenizer.js').TokenizerJSON

const HERE = dirname(fileURLToPath(import.meta.url))

interface Fixture {
  text: string
  ids: number[]
  decoded: string
}

const fixtures: Fixture[] = JSON.parse(readFileSync(resolve(HERE, 'fixtures.json'), 'utf8'))
const tokenizerJson: TokenizerJSON = JSON.parse(
  readFileSync(resolve(HERE, 'tokenizer.json'), 'utf8'),
)
const tok = createTokenizer(tokenizerJson)

// ---------------------------------------------------------------------------
// Known, intentional decode divergences from the HF reference.
//
// The app's decode() strips ALL chat-marker tokens (<s>, </s>, <pad>, <|...|>)
// so streamed output never shows template noise. HF's skip_special_tokens
// only skips tokens its config flags as special — and this tokenizer.json
// marks </s> as special:false, so HF keeps a literal "</s>" in the output
// where the app (deliberately) drops it. Encode is NOT allowed to diverge.
// ---------------------------------------------------------------------------
const DECODE_DIVERGENT = new Map<string, string>([
  // fixture text → expected APP output (HF reference keeps "</s>")
  ['<s>bos then text</s>', 'bos then text'],
])

const label = (text: string) =>
  JSON.stringify(text.length > 48 ? text.slice(0, 48) + '…' : text)

describe('encode() matches the HuggingFace reference', () => {
  for (const { text, ids } of fixtures) {
    test(label(text), () => {
      expect(tok.encode(text)).toEqual(ids)
    })
  }
})

describe('decode() matches the HuggingFace reference', () => {
  for (const { text, ids, decoded } of fixtures) {
    const divergent = DECODE_DIVERGENT.get(text)
    if (divergent !== undefined) {
      test(`${label(text)} (known-divergent: app strips </s>, HF keeps it)`, () => {
        expect(tok.decode(ids)).not.toBe(decoded)
        expect(tok.decode(ids)).toBe(divergent)
      })
    } else {
      test(label(text), () => {
        expect(tok.decode(ids)).toBe(decoded)
      })
    }
  }
})

describe('encode/decode round-trip', () => {
  // decode(encode(text)) must reproduce the reference's decoded form (which
  // equals `text` for anything without special tokens).
  for (const { text, decoded } of fixtures) {
    const expected = DECODE_DIVERGENT.get(text) ?? decoded
    test(label(text), () => {
      expect(tok.decode(tok.encode(text))).toBe(expected)
    })
  }
})

describe('buildChatPrompt', () => {
  test('system+user template matches the reference fixture ids', () => {
    // Same messages the fixture-generation script used.
    const fixture = fixtures.find((f) => f.text.startsWith('<|system|>\nYou are a helpful'))
    expect(fixture).toBeDefined()
    const ids = buildChatPrompt(
      [
        { role: 'system', content: 'You are a helpful assistant.' },
        { role: 'user', content: 'What is the capital of France?' },
      ],
      tok,
    )
    expect(ids).toEqual(fixture!.ids)
  })

  test('multi-turn template matches the reference fixture ids', () => {
    const fixture = fixtures.find((f) => f.text.startsWith('<|user|>\nWrite a haiku'))
    expect(fixture).toBeDefined()
    const ids = buildChatPrompt(
      [
        { role: 'user', content: 'Write a haiku about GPUs.' },
        { role: 'assistant', content: 'Warm silicon hums' },
        { role: 'user', content: 'Continue it' },
      ],
      tok,
    )
    expect(ids).toEqual(fixture!.ids)
  })
})

describe('tokenizer basics', () => {
  test('bos/eos ids', () => {
    expect(tok.bosId).toBe(1)
    expect(tok.eosId).toBe(2)
  })

  test('newline encodes via byte fallback, not <unk>', () => {
    const ids = tok.encode('a\nb')
    expect(ids).toContain(13) // <0x0A>
    expect(ids).not.toContain(0) // <unk>
  })

  test('decode preserves intentional leading whitespace beyond the SPM prefix', () => {
    // "  x" → ▁▁▁x-ish: exactly one prefix space is stripped, no more.
    expect(tok.decode(tok.encode('  two leading'))).toBe('  two leading')
  })
})
