/**
 * SWARM LINK BUILDER — the entrance's second door.
 *
 * The character screen above sells one model in one tab. A room can hold more
 * than that: `layerRange` builds ONE stage of a model, so a stack too big for
 * a single machine can be cut into ranges, one machine per range, with the
 * residual hopping between them. Nothing on the entrance said so.
 *
 * The builder exists because the URL grammar is genuinely hard to type. The
 * query must come BEFORE the fragment — `share.html?model=X&layers=13-26#room`
 * — and writing it the other way round is not an error, it is a DIFFERENT
 * ROLE: location.search is empty, location.hash no longer matches a room id,
 * and share.ts falls through to the host branch and opens a brand-new room.
 * Two machines then sit in two rooms waiting for each other, with nothing on
 * either screen saying why. That cost a real user an hour on 2026-08-29. The
 * links here are generated by room-url.ts, which share.ts routes on, so a
 * generated URL and the page that reads it cannot disagree.
 *
 * Every model, every layer count and the splittable-or-not rule come from the
 * registry. No list is typed here — the entrance has been stale that way
 * before.
 *
 * Progressive enhancement: index.html carries the prose and a plain link to
 * share.html; this module only replaces the builder placeholder, and it
 * touches no WebGPU, so it runs on a browser that cannot host at all (that
 * browser can still be the guest).
 */

import { SHIPPED_MODELS, canSplitAcrossDevices, modelBranding } from './zero-tvm/model-registry.js'
import { roomIdFrom, swarmUrls, type SwarmStop } from './zero-tvm/room-url.js'

/** Models a split can actually be built for — the loader refuses a layerRange
 *  on an MLC checkpoint, so offering one here would hand out a URL that throws
 *  at boot. `pending` models are hidden for the same reason the roster hides
 *  them: a link is a claim the model runs. */
const SPLITTABLE = SHIPPED_MODELS.filter(
  ({ spec }) => canSplitAcrossDevices(spec) && !modelBranding(spec).pending,
)

/** "35B-A3B MoE · 3-bit experts" — the part after the separator is the build,
 *  and it is the only thing telling the two Qwen3.6 chips apart. */
const buildOf = (params: string): string => {
  const i = params.indexOf(' · ')
  return i < 0 ? '' : params.slice(i + 3)
}

/** How many machines to cut the stack into. Words rather than a numeral row:
 *  this is the entrance, where every printed figure has to be defensible, and
 *  the count that matters is in the URL below anyway. */
const SPLITS: ReadonlyArray<{ n: number; label: string }> = [
  { n: 2, label: 'Two machines' },
  { n: 3, label: 'Three machines' },
  { n: 4, label: 'Four machines' },
]

const ROLE_NOTE: Record<SwarmStop['role'], string> = {
  host: 'Opens the room and holds the start of the model. The page asks before it downloads anything.',
  helper: 'Joins that room holding its own range. It answers no chat of its own — it runs its layers and hands the residual back.',
  guest: 'The link to hand out. Chats with the assembled model; downloads nothing, needs no WebGPU.',
}

const ordinal = (i: number): string =>
  ['First', 'Second', 'Third', 'Fourth', 'Fifth'][i] ?? `Machine ${i + 1}`

function mountSwarmBuilder(host: HTMLElement): void {
  if (SPLITTABLE.length === 0) return

  let mi = 0
  let si = 0

  host.innerHTML = `
    <div class="mb-panel sw-panel">
      <div class="mb-row-label">Model</div>
      <div class="mb-variants sw-models" role="tablist" aria-label="Model to split"></div>
      <div class="mb-row-label">Split across</div>
      <div class="mb-variants sw-splits" role="tablist" aria-label="How many machines"></div>
      <div class="mb-row-label sw-step">1 · Open on the machine that holds the start</div>
      <div class="sw-stops sw-host"></div>
      <div class="mb-row-label sw-step">2 · Paste the room link that machine shows</div>
      <input class="sw-room" type="text" spellcheck="false" autocomplete="off"
             aria-label="Room link from the first machine"
             placeholder="https://…/share.html#…">
      <p class="sw-hint">Keep this page open — the rest of the links cannot be
        written until that room exists.</p>
      <div class="mb-row-label sw-step">3 · Open on every other machine</div>
      <div class="sw-stops sw-rest"></div>
    </div>`

  const el = <T extends Element>(sel: string): T => host.querySelector<T>(sel)!
  const roomInput = el<HTMLInputElement>('.sw-room')

  el('.sw-models').innerHTML = SPLITTABLE.map(({ spec }, i) => {
    const b = modelBranding(spec)
    const build = buildOf(b.params)
    return `<button type="button" class="mb-variant sw-model" data-i="${i}" role="tab"`
      + ` aria-selected="${i === 0}">${b.name}${build ? ` · ${build}` : ''}</button>`
  }).join('')

  el('.sw-splits').innerHTML = SPLITS.map((s, i) =>
    `<button type="button" class="mb-variant sw-split" data-i="${i}" role="tab"`
    + ` aria-selected="${i === 0}">${s.label}</button>`).join('')

  /** The room id out of whatever was pasted: a full link, or the id alone.
   *  Validated by the SAME test share.ts applies to location.hash, so a
   *  half-copied link is refused here rather than producing a URL that
   *  silently opens a second room. */
  function pastedRoom(): string | null {
    const raw = roomInput.value.trim()
    if (!raw) return null
    const hash = raw.includes('#') ? raw.slice(raw.indexOf('#')) : `#${raw}`
    return roomIdFrom(hash)
  }

  function stopRow(stop: SwarmStop, index: number): string {
    const who = stop.role === 'guest' ? 'Anyone else' : `${ordinal(index)} machine`
    // A guest holds no layers at all, so the range slot is simply absent —
    // "no layers" read as a fault rather than as the point of the row.
    const tag = stop.range ? `${stop.role} · layers ${stop.range.start}–${stop.range.end}` : stop.role
    const head = `<div class="sw-stop-head"><b>${who}</b><span>${tag}</span></div>`
    const note = `<p class="sw-note">${ROLE_NOTE[stop.role]}</p>`
    if (stop.url === null) {
      return `<div class="sw-stop" data-role="${stop.role}">${head}
        <div class="sw-linkrow"><input readonly disabled value="waiting for the room link above"></div>
        ${note}</div>`
    }
    // The room id reaching this markup has passed roomIdFrom's anchored
    // [A-Za-z0-9_-]{16,64} test, so a pasted string cannot close the attribute
    // — the one remote-controlled part of these URLs is validated before it is
    // written, not after (lens 2026-08-17).
    // target=_blank on every link, the host's included: the room link has to
    // be pasted back into THIS page, so navigating away from it is the one
    // move that breaks the sequence.
    return `<div class="sw-stop" data-role="${stop.role}">${head}
      <div class="sw-linkrow">
        <input readonly value="${stop.url}" aria-label="${who} — ${stop.role} link">
        <button type="button" class="cs-chat-tool sw-copy">Copy</button>
        <a class="cs-chat-tool sw-open" href="${stop.url}" target="_blank" rel="noopener">Open ↗</a>
      </div>
      ${note}</div>`
  }

  function paint(): void {
    const { param, spec } = SPLITTABLE[mi]
    const machines = SPLITS[si].n
    const stops = swarmUrls({
      origin: location.origin,
      param,
      layers: spec.layers,
      machines,
      room: pastedRoom(),
      // State the context EXPLICITLY, even though it is this build's own
      // default. Two machines in one swarm can be on two deploys of the site,
      // and a compiled default that moved between them would give the stages
      // differently sized KV caches for the same conversation (room-url.ts's
      // ctxFor). A number in the link cannot drift; a default can.
      ctx: spec.maxContext,
    })
    el('.sw-host').innerHTML = stopRow(stops[0], 0)
    el('.sw-rest').innerHTML = stops.slice(1).map((s, i) => stopRow(s, i + 1)).join('')
    // No placeholder link is offered before the room exists: a fragment that
    // is not a room id routes to the HOST branch, so a copyable placeholder
    // would be the silent second-room bug with a Copy button on it.
    el('.sw-hint').textContent = pastedRoom()
      ? 'Room found — every link below joins it.'
      : 'Keep this page open. The links below cannot be written until that room exists.'
  }

  host.addEventListener('click', (e) => {
    const t = e.target as HTMLElement
    const model = t.closest<HTMLElement>('.sw-model')
    if (model) {
      mi = Number(model.dataset.i)
      for (const b of host.querySelectorAll<HTMLElement>('.sw-model')) {
        b.setAttribute('aria-selected', String(Number(b.dataset.i) === mi))
      }
      paint()
      return
    }
    const split = t.closest<HTMLElement>('.sw-split')
    if (split) {
      si = Number(split.dataset.i)
      for (const b of host.querySelectorAll<HTMLElement>('.sw-split')) {
        b.setAttribute('aria-selected', String(Number(b.dataset.i) === si))
      }
      paint()
      return
    }
    const copy = t.closest<HTMLElement>('.sw-copy')
    if (copy) {
      const input = copy.parentElement?.querySelector('input')
      if (!input) return
      void navigator.clipboard.writeText(input.value)
      copy.textContent = 'Copied'
      setTimeout(() => { copy.textContent = 'Copy' }, 1200)
    }
  })

  roomInput.addEventListener('input', paint)
  paint()
}

const mount = document.getElementById('swarm-builder')
if (mount) mountSwarmBuilder(mount)
