/**
 * SWARM — the entrance's second STAGE MODE, not a section under it.
 *
 * It used to be a documentation block below the character screen: its own
 * heading, its own band of explainer cards, its own panel. It read as a manual
 * stapled to a game screen, and — worse — nothing on the screen connected the
 * amber "needs ~N GB free RAM" line to the one thing that answers it. The
 * doorway is that line now (landing.ts appends the ⟁ control to it), and what
 * it opens is a mode of the same stage: `cs-swarm`, parallel to `cs-chatting`.
 *
 * So this file owns no chrome of its own. The role rows go into the sheet the
 * stats live in, the explainer cards become the character's passives in the
 * sheet's own `.mb-abilities` component, and the machine count is drawn on the
 * summoning ring — N arcs, one per machine, each lighting when that machine's
 * URL becomes writable.
 *
 * The builder exists because the URL grammar is genuinely hard to type. The
 * query must come BEFORE the fragment — `share.html?model=X&layers=13-26#room`
 * — and writing it the other way round is not an error, it is a DIFFERENT
 * ROLE: location.search is empty, location.hash no longer matches a room id,
 * and share.ts falls through to the host branch and opens a brand-new room.
 * Two machines then sit in two rooms waiting for each other, with nothing on
 * either screen saying why. That cost a real user an hour on 2026-08-29. The
 * links here are generated by room-url.ts, which share.ts routes on, so a
 * generated URL and the page that reads it cannot disagree.
 *
 * Every layer count and the splittable-or-not rule come from the registry. No
 * list is typed here — the entrance has been stale that way before.
 *
 * Progressive enhancement: index.html still carries the prose and a plain link
 * to share.html in a `#swarm` section, which landing.ts hides only once it has
 * rendered the scene. This module touches no WebGPU, so it runs on a browser
 * that cannot host at all (that browser can still be the guest).
 */

import type { ModelSpec } from './compiler/model-spec.js'
import { roomIdFrom, swarmUrls, type SwarmStop } from './zero-tvm/room-url.js'

export interface SwarmOptions {
  /** The .cs-root the select screen rendered into. */
  root: HTMLElement
  /** `#models .mb-panel` — the stat sheet. The role rows live in it. */
  panel: HTMLElement
  /** The model on stage. Its layer count sets every range. */
  spec: ModelSpec
  /** `?model=` value, from the registry — never a hand-typed id. */
  param: string
  /** The character on stage cannot be split any more (the roster moved to an
   *  MLC checkpoint) — the mode has nothing left to show. */
  onExit: () => void
}

export interface SwarmHandle {
  /** Re-point at the model now on stage. A no-op when it has not changed, so
   *  a repaint from the cache probe cannot wipe a pasted room link. */
  refresh(spec: ModelSpec, param: string): void
  destroy(): void
}

/** How many machines to cut the stack into. Words rather than a numeral row:
 *  this is the entrance, where every printed figure has to be defensible, and
 *  the count that matters is drawn on the ring and written into the URLs. */
const SPLITS: ReadonlyArray<{ n: number; label: string }> = [
  { n: 2, label: 'Two machines' },
  { n: 3, label: 'Three machines' },
  { n: 4, label: 'Four machines' },
]

const ROLE_NOTE: Record<SwarmStop['role'], string> = {
  host: 'Opens the room and holds the start of the model. It asks before it downloads anything.',
  helper: 'Joins that room holding its own range. It answers no chat of its own — it runs its layers and hands the residual back.',
  guest: 'The link to hand out. Chats with the assembled model; downloads nothing, needs no WebGPU.',
}

/** The four things a reader has to believe before the links mean anything.
 *  They were four cards in a grid; the sheet already has a component for a
 *  character's passives, and these are the swarm's. */
const PASSIVES: ReadonlyArray<{ name: string; desc: string }> = [
  { name: 'Split by layer', desc: 'each machine downloads only the layers it holds — the one that starts the model carries the embedding, the one that ends it carries the output head' },
  { name: 'Tokens hop', desc: 'what crosses between machines is the bare residual, one hand-off per token, on its own data channel' },
  { name: 'Guests just talk', desc: 'the room link opens a chat and nothing else — no WebGPU, no download, nothing runs on their machine' },
  { name: 'Weights spread', desc: 'a guest can copy the cached weights from the machine serving it, over a second channel, and then serve the room itself' },
]

const ordinal = (i: number): string =>
  ['First', 'Second', 'Third', 'Fourth', 'Fifth'][i] ?? `Machine ${i + 1}`

/** The gap between two arcs of the summoning ring, in degrees. Small enough
 *  that the ring still reads as one circle, wide enough that two machines are
 *  two things. */
const ARC_GAP = 9

export function mountSwarm(o: SwarmOptions): SwarmHandle {
  let spec = o.spec
  let param = o.param
  /** Selected machine count (index into SPLITS). Survives refresh — it is a
   *  choice about the room, not about the character. */
  let si = 0

  const rows = document.createElement('div')
  rows.className = 'sw-rows'
  // Not a wrapper element: the sheet's row-stagger animates the panel's DIRECT
  // children, so these rows are appended to the panel itself and the container
  // is only a handle for removing them again.
  const html = `
    <div class="mb-row-label sw-row" style="--i:0">Split across</div>
    <div class="mb-variants sw-splits sw-row" style="--i:1" role="tablist" aria-label="How many machines"></div>
    <div class="mb-row-label sw-row" style="--i:2">The start</div>
    <div class="sw-stops sw-host sw-row" style="--i:3"></div>
    <div class="mb-row-label sw-row" style="--i:4">Room link from it</div>
    <input class="sw-room sw-row" style="--i:5" type="text" spellcheck="false" autocomplete="off"
           aria-label="Room link from the first machine" placeholder="https://…/share.html#…">
    <p class="sw-hint sw-row" style="--i:6"></p>
    <div class="mb-row-label sw-row" style="--i:7">The rest</div>
    <div class="sw-stops sw-rest sw-row" style="--i:8"></div>
    <ul class="mb-abilities sw-row" style="--i:9">${PASSIVES.map((p) =>
      `<li><b>${p.name}</b><span>${p.desc}</span></li>`).join('')}</ul>
    <button type="button" class="sw-exit sw-row" style="--i:10">⟨ Back to one machine</button>`
  rows.innerHTML = html
  const mine = [...rows.children] as HTMLElement[]
  for (const n of mine) o.panel.appendChild(n)

  const el = <T extends Element>(sel: string): T => o.panel.querySelector<T>(sel)!
  const roomInput = el<HTMLInputElement>('.sw-room')

  el('.sw-splits').innerHTML = SPLITS.map((s, i) =>
    `<button type="button" class="mb-variant sw-split" data-i="${i}" role="tab"`
    + ` aria-selected="${i === si}">${s.label}</button>`).join('')

  // ── the ring ────────────────────────────────────────────────────────
  // The machine count is not a figure on a chip, it is the shape of the
  // summoning circle: N arcs, dark until that machine's URL can be written.
  const pedestal = o.root.querySelector<HTMLElement>('.mb-pedestal')
  const art = o.root.querySelector<HTMLElement>('.mb-art')
  const arcs: HTMLElement[] = []

  function drawArcs(n: number): void {
    for (const a of arcs.splice(0)) a.remove()
    if (!pedestal) return
    const step = 360 / n
    for (let i = 0; i < n; i++) {
      const a = document.createElement('i')
      a.className = 'sw-arc'
      a.style.setProperty('--a0', `${i * step + ARC_GAP / 2}deg`)
      a.style.setProperty('--a1', `${(i + 1) * step - ARC_GAP / 2}deg`)
      pedestal.appendChild(a)
      arcs.push(a)
    }
  }

  /** An arc lights when the machine it stands for has a URL to open. The first
   *  one always does; the rest wait on the room, which is exactly the thing
   *  the sequence is blocked on. */
  function lightArcs(stops: SwarmStop[]): void {
    const machines = stops.filter((s) => s.role !== 'guest')
    let lit = 0
    machines.forEach((s, i) => {
      const on = s.url !== null
      if (on) lit++
      // Retrigger ringFlash only on the transition — a repaint must not
      // re-flash a circle that has been lit the whole time.
      if (on !== arcs[i]?.hasAttribute('data-lit')) arcs[i]?.toggleAttribute('data-lit', on)
    })
    // Every machine has its link: the circle runs the armed sweep, the same
    // ceremony a cached character's ring runs.
    art?.toggleAttribute('data-swarm-armed', lit === machines.length && lit > 0)
  }

  // ── the links ───────────────────────────────────────────────────────
  /** The room id out of whatever was pasted: a full link, or the id alone.
   *  Validated by the SAME test share.ts applies to location.hash, so a
   *  half-copied link is refused here rather than producing a URL that
   *  silently opens a second room. */
  function pastedRoom(): string | null {
    const raw = roomInput.value.trim()
    if (!raw) return null
    const hash = raw.includes('#') ? raw.slice(raw.indexOf('#')) : `#${raw}`
    return roomIdFrom(hash)
  }

  function stopRow(stop: SwarmStop, index: number, note: boolean): string {
    const who = stop.role === 'guest' ? 'Anyone else' : `${ordinal(index)} machine`
    // A guest holds no layers at all, so the range slot is simply absent —
    // "no layers" read as a fault rather than as the point of the row.
    const tag = stop.range ? `${stop.role} · layers ${stop.range.start}–${stop.range.end}` : stop.role
    const head = `<div class="sw-stop-head"><b>${who}</b><span>${tag}</span></div>`
    // Every helper carries the same sentence — printing it three times was the
    // documentation tell. It is stated once, on the first one.
    const body = note ? `<p class="sw-note">${ROLE_NOTE[stop.role]}</p>` : ''
    if (stop.url === null) {
      return `<div class="sw-stop" data-role="${stop.role}">${head}
        <div class="sw-linkrow"><input readonly disabled value="waiting for the room link"></div>
        ${body}</div>`
    }
    // The room id reaching this markup has passed roomIdFrom's anchored
    // [A-Za-z0-9_-]{16,64} test, so a pasted string cannot close the attribute
    // — the one remote-controlled part of these URLs is validated before it is
    // written, not after (lens 2026-08-17).
    // target=_blank on every link, the host's included: the room link has to
    // be pasted back into THIS page, so navigating away from it is the one
    // move that breaks the sequence.
    return `<div class="sw-stop" data-role="${stop.role}">${head}
      <div class="sw-linkrow">
        <input readonly value="${stop.url}" aria-label="${who} — ${stop.role} link">
        <button type="button" class="cs-chat-tool sw-copy">Copy</button>
        <a class="cs-chat-tool sw-open" href="${stop.url}" target="_blank" rel="noopener">Open ↗</a>
      </div>
      ${body}</div>`
  }

  function paint(): void {
    const machines = SPLITS[si].n
    const stops = swarmUrls({
      origin: location.origin,
      param,
      layers: spec.layers,
      machines,
      room: pastedRoom(),
      // State the context EXPLICITLY, even though it is this build's own
      // default. Two machines in one swarm can be on two deploys of the site,
      // and a compiled default that moved between them would give the stages
      // differently sized KV caches for the same conversation (room-url.ts's
      // ctxFor). A number in the link cannot drift; a default can.
      ctx: spec.maxContext,
    })
    el('.sw-host').innerHTML = stopRow(stops[0], 0, true)
    el('.sw-rest').innerHTML = stops.slice(1)
      .map((s, i) => stopRow(s, i + 1, i === 0 || s.role === 'guest')).join('')
    // No placeholder link is offered before the room exists: a fragment that
    // is not a room id routes to the HOST branch, so a copyable placeholder
    // would be the silent second-room bug with a Copy button on it.
    el('.sw-hint').textContent = pastedRoom()
      ? 'Room found — every link below joins it.'
      : 'Keep this page open. The links below cannot be written until that room exists.'
    lightArcs(stops)
  }

  const onClick = (e: Event): void => {
    const t = e.target as HTMLElement
    const split = t.closest<HTMLElement>('.sw-split')
    if (split) {
      si = Number(split.dataset.i)
      for (const b of o.panel.querySelectorAll<HTMLElement>('.sw-split')) {
        b.setAttribute('aria-selected', String(Number(b.dataset.i) === si))
      }
      drawArcs(SPLITS[si].n)
      paint()
      // paint() re-creates the chips' siblings, not the chips — but the ring
      // redraw is the visible answer, and focus stays where it was.
      return
    }
    const copy = t.closest<HTMLElement>('.sw-copy')
    if (copy) {
      const input = copy.parentElement?.querySelector('input')
      if (!input) return
      void navigator.clipboard.writeText(input.value)
      copy.textContent = 'Copied'
      setTimeout(() => { copy.textContent = 'Copy' }, 1200)
      return
    }
    if (t.closest('.sw-exit')) o.onExit()
  }
  o.panel.addEventListener('click', onClick)
  roomInput.addEventListener('input', paint)

  drawArcs(SPLITS[si].n)
  paint()

  return {
    refresh(nextSpec: ModelSpec, nextParam: string): void {
      if (nextSpec.id === spec.id && nextParam === param) return
      spec = nextSpec
      param = nextParam
      // A different model is a different set of links; the room the previous
      // one opened cannot serve it.
      roomInput.value = ''
      paint()
    },
    destroy(): void {
      o.panel.removeEventListener('click', onClick)
      for (const n of mine) n.remove()
      for (const a of arcs.splice(0)) a.remove()
      art?.removeAttribute('data-swarm-armed')
    },
  }
}
