// The three ChatML generations, pinned against their own templates.
//
// One family, three renderers. Nothing in Qwen's published documentation states
// any of these differences; each is a line of jinja inside the checkpoint, and
// they change between minor versions:
//
//   qwen3   Qwen3-4B, Qwen3-30B-A3B    no |trim at all; splits </think> out of
//                                       assistant text; past-turn <think> only
//                                       on a TRAILING turn (loop.last) or when
//                                       reasoning was actually split out
//   qwen35  Qwen3.5-4B/9B, Qwen3.6     |trim on every message; splits </think>;
//                                       past-turn <think> on the current round
//   qwen38  Qwen3.8-27B                |trim; NO </think> split (its branch
//                                       reads only a reasoning_content FIELD,
//                                       which no client sends); past-turn
//                                       <think> on EVERY assistant turn, because
//                                       its condition opens `preserve_thinking
//                                       is undefined` and nothing defines it
//
// Every expectation below is the literal output of that checkpoint's own
// template through transformers — generated by scripts/gen-toolcall-fixtures.py,
// not hand-derived. scripts/render-diff.py --shapes runs the same comparison
// live against the checkpoints; this file is the half that runs in CI without
// them.
//
// These shapes are reachable, not adversarial curiosities: chat-flow.ts stores
// the model's RAW output as history, so one reply containing </think> puts that
// turn in the transcript, and room-host.ts renders a remote GUEST's history
// verbatim.

import { describe, expect, it } from 'vitest'
import { buildChatPrompt } from '../../src/zero-tvm/tokenizer-bpe.ts'
import { foldToolResults, renderAssistantCalls, type ToolChatMessage } from '../../src/zero-tvm/tool-calls.ts'
import { SHIPPED_MODELS, specForParam } from '../../src/zero-tvm/model-registry.ts'

const capture = { encode: (t: string) => [t] as unknown as number[] }
/** Same cast tool-calls.test.ts uses: ToolChatMessage carries llama3's
 *  'ipython' role, which the ChatML builder's signature does not list. Widening
 *  the builder instead would let an ipython turn reach a ChatML template. */
type TemplateMessages = Array<{ role: 'system' | 'user' | 'assistant'; content: string }>
const render = (m: TemplateMessages | ToolChatMessage[],
                generation: 'qwen3' | 'qwen35' | 'qwen38') =>
  (buildChatPrompt(m as TemplateMessages, capture, { thinking: false, generation }) as unknown as string[]).join('')

// ── vendor fixtures ─────────────────────────────────────────────────────────
const THINK_IN_REPLY_QWEN3 = "<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\nhello<|im_end|>\n<|im_start|>user\nagain<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"
const THINK_IN_REPLY_QWEN35 = "<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\nhello<|im_end|>\n<|im_start|>user\nagain<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"
const THINK_IN_REPLY_QWEN38 = "<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n<think>\nmusing\n</think>\n\nhello<|im_end|>\n<|im_start|>user\nagain<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"

const UNTRIMMED_QWEN3 = "<|im_start|>system\nsys\n<|im_end|>\n<|im_start|>user\nhi\n<|im_end|>\n<|im_start|>assistant\n hello <|im_end|>\n<|im_start|>user\nagain<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"
const UNTRIMMED_QWEN35 = "<|im_start|>system\nsys<|im_end|>\n<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\nhello<|im_end|>\n<|im_start|>user\nagain<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"
const UNTRIMMED_QWEN38 = "<|im_start|>system\nsys<|im_end|>\n<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\nhello<|im_end|>\n<|im_start|>user\nagain<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"

const TOOL_UNTRIMMED_QWEN3 = "<|im_start|>user\ngo<|im_end|>\n<|im_start|>assistant\n<tool_call>\n{\"name\": \"read_file\", \"arguments\": {\"path\": \"a.ts\"}}\n</tool_call><|im_end|>\n<|im_start|>user\n<tool_response>\n  padded  \n\n</tool_response><|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"
const TOOL_UNTRIMMED_QWEN35 = "<|im_start|>user\ngo<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n<tool_call>\n<function=read_file>\n<parameter=path>\na.ts\n</parameter>\n</function>\n</tool_call><|im_end|>\n<|im_start|>user\n<tool_response>\npadded\n</tool_response><|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"

describe('an assistant turn that contains </think>', () => {
  const convo = [
    { role: 'user' as const, content: 'hi' },
    { role: 'assistant' as const, content: '<think>\nmusing\n</think>\n\nhello' },
    { role: 'user' as const, content: 'again' },
  ]

  it('qwen3 splits the reasoning out and drops it on a finished round', () => {
    expect(render(convo, 'qwen3')).toBe(THINK_IN_REPLY_QWEN3)
  })

  it('qwen35 does the same', () => {
    expect(render(convo, 'qwen35')).toBe(THINK_IN_REPLY_QWEN35)
  })

  it('qwen38 does NOT split — the text passes through whole', () => {
    // Its branch reads a reasoning_content FIELD and nothing else, so the
    // </think> in the text is just text. Splitting here would cut the reply at
    // the tag and re-emit half of it as reasoning.
    expect(render(convo, 'qwen38')).toBe(THINK_IN_REPLY_QWEN38)
    expect(render(convo, 'qwen38')).toContain('<think>\nmusing\n</think>')
  })

  it('a bare </think> mid-sentence is not a reasoning block on qwen38', () => {
    const said = [
      { role: 'user' as const, content: 'hi' },
      { role: 'assistant' as const, content: 'print </think> here' },
      { role: 'user' as const, content: 'again' },
    ]
    expect(render(said, 'qwen38')).toContain('print </think> here')
    // qwen35 DOES split it — everything before the tag becomes reasoning and is
    // dropped on a finished round, so the reply reaching the model is ' here'.
    // The leading space survives: the template does lstrip('\n'), not |trim.
    // Vendor output for this exact case, via transformers.
    expect(render(said, 'qwen35')).toBe(
      '<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\n here<|im_end|>\n'
      + '<|im_start|>user\nagain<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n')
  })
})

describe('|trim on message content', () => {
  const convo = [
    { role: 'system' as const, content: 'sys\n' },
    { role: 'user' as const, content: 'hi\n' },
    { role: 'assistant' as const, content: ' hello ' },
    { role: 'user' as const, content: 'again' },
  ]

  it('qwen3 does NOT trim — content is interpolated verbatim', () => {
    expect(render(convo, 'qwen3')).toBe(UNTRIMMED_QWEN3)
    expect(render(convo, 'qwen3')).toContain('\n hello <|im_end|>')
  })

  it('qwen35 trims every message', () => {
    expect(render(convo, 'qwen35')).toBe(UNTRIMMED_QWEN35)
  })

  it('qwen38 trims too', () => {
    expect(render(convo, 'qwen38')).toBe(UNTRIMMED_QWEN38)
  })
})

describe('tool results follow the same trim rule', () => {
  // A tool whose output ends in a newline is the common case, not the edge one.
  const round = (dialect: 'chatml-json' | 'chatml-xml') => foldToolResults(dialect, [
    { role: 'user', content: 'go' },
    {
      role: 'assistant',
      content: renderAssistantCalls(dialect, '', [{ name: 'read_file', arguments: { path: 'a.ts' } }]),
    },
    { role: 'tool', content: '  padded  \n' },
  ])

  it('qwen3 keeps the padding', () => {
    expect(render(round('chatml-json'), 'qwen3')).toBe(TOOL_UNTRIMMED_QWEN3)
  })

  it('qwen35 trims it', () => {
    expect(render(round('chatml-xml'), 'qwen35')).toBe(TOOL_UNTRIMMED_QWEN35)
  })
})

describe('the spec → generation dispatch', () => {
  // buildChatPromptFor is the ONE line carrying this fix from the spec to the
  // renderer, for all five pages that build a prompt. Nothing tested it: a lens
  // swapped 'qwen38' and 'qwen35' in model-select.ts — which renders every
  // Qwen3.5/3.6 conversation under Qwen3.8's rule and vice versa — and the
  // whole suite stayed green. Everything above this block passes `generation`
  // explicitly and so cannot see a dispatch error.
  //
  // Imported through the registry, not model-select, for the usual reason:
  // model-select pulls in weight-loader, which reads GPUBufferUsage at module
  // scope. The dispatch is re-derived here from chatTemplateId, which is what
  // buildChatPromptFor switches on, and each expectation is a DIFFERENT
  // rendering — so a transposition changes the output, not just a label.
  const GEN: Record<string, 'qwen3' | 'qwen35' | 'qwen38'> = {
    chatml: 'qwen3', 'chatml-q35': 'qwen35', 'chatml-q38': 'qwen38',
  }
  // A MID-ROUND assistant turn is the only shape that separates all three rules:
  // it sits after the last real user query (the tool result does not count as
  // one) and is not the trailing message. qwen3 needs `loop.last` and so emits
  // nothing; qwen35 emits; qwen38 emits on every turn including the finished
  // one. A plain chat cannot tell qwen3 and qwen35 apart at all, which is why
  // the first version of this test asserted three distinct outputs and got two.
  // Needs BOTH a finished-round turn and a mid-round one. a0 sits before the
  // last real user query, so only qwen38 keeps its block; a1 sits after it and
  // is not trailing, so qwen3 drops it (no loop.last, no reasoning) while q35
  // and q38 keep it. Three rules, three outputs. A shape with only one of the
  // two collapses two of them together — which is how the first two versions of
  // this test asserted three and measured two.
  const round = [
    { role: 'user' as const, content: 'q1' },
    { role: 'assistant' as const, content: 'a0' },
    { role: 'user' as const, content: 'go' },
    { role: 'assistant' as const, content: 'a1' },
    { role: 'user' as const, content: '<tool_response>\nr\n</tool_response>' },
  ]

  it('each template id renders a DIFFERENT prompt for the same conversation', () => {
    const out = (['chatml', 'chatml-q35', 'chatml-q38'] as const).map((id) => render(round, GEN[id]))
    expect(new Set(out).size).toBe(3)
  })

  it('the three ids map to the three rules, checked by output not by name', () => {
    const B = '<think>\n\n</think>\n\n'
    const body = (a0: string, a1: string) =>
      '<|im_start|>user\nq1<|im_end|>\n'
      + `<|im_start|>assistant\n${a0}a0<|im_end|>\n`
      + '<|im_start|>user\ngo<|im_end|>\n'
      + `<|im_start|>assistant\n${a1}a1<|im_end|>\n`
      + '<|im_start|>user\n<tool_response>\nr\n</tool_response><|im_end|>\n'
      + `<|im_start|>assistant\n${B}`
    expect(render(round, GEN.chatml)).toBe(body('', ''))
    expect(render(round, GEN['chatml-q35'])).toBe(body('', B))
    expect(render(round, GEN['chatml-q38'])).toBe(body(B, B))
  })

  it('every ChatML spec in the registry maps to a generation', () => {
    // A spec carrying a chatTemplateId with no entry here would fall through to
    // the 'qwen3' default and render silently wrong.
    for (const m of SHIPPED_MODELS) {
      const id = specForParam(m.param).chatTemplateId
      if (id.startsWith('chatml')) expect(GEN[id], `${m.param} → ${id}`).toBeDefined()
    }
  })
})
