// PREFIX REUSE — the rules that decide whether a turn re-prefills 20,000
// tokens or 40.
//
// Every expectation below is hand-derived from the rule as stated in
// engine-core.ts's own comment, NOT from running the extracted code. A table
// generated by the implementation would pass against any implementation,
// including a wrong one, which is the whole reason this file exists
// (docs/PAGING_PLAN.md §0.1).
//
// The rules, restated:
//   pure attention  reuse = min(LCP, len-1)
//   hybrid          reuse = LCP, but ONLY when gdnStatePos === absorbed.length
//                   AND LCP === absorbed.length AND LCP <= len-1; else 0
//   any             reuse = 0 when !prefixReuse, !absorbedValid, or len === 0
//
// Until now the only assertion on any of this was checkReuse() in
// bench-console.ts, which needs a browser, a loaded model, 48 decoded tokens
// and ?chunk=0.

import { describe, expect, it } from 'vitest'
import { reuseStart, rewindSlot, dropSnapshotsAbove, noteAbsorbed, type ReuseState } from '../../src/zero-tvm/prefix-reuse.ts'

const state = (over: Partial<ReuseState> = {}): ReuseState => ({
  absorbed: [], absorbedValid: true, prefixReuse: true, hybrid: false, gdnStatePos: 0, ...over,
})

describe('reuseStart — pure attention', () => {
  it('reuses the whole absorbed prefix but always leaves one token to run', () => {
    // The final prompt token must run: it produces the first argmax. Reusing
    // all 5 would decode from a position whose logits were never computed.
    const s = state({ absorbed: [1, 2, 3, 4, 5] })
    expect(reuseStart(s, [1, 2, 3, 4, 5])).toBe(4)
    expect(reuseStart(s, [1, 2, 3, 4, 5, 6, 7])).toBe(5)
  })

  it('stops at the first divergence, not at the length', () => {
    const s = state({ absorbed: [1, 2, 3, 4, 5] })
    expect(reuseStart(s, [1, 2, 9, 4, 5, 6])).toBe(2)
    expect(reuseStart(s, [9, 2, 3])).toBe(0)
  })

  it('is capped by the shorter of the two, then by len-1', () => {
    expect(reuseStart(state({ absorbed: [1, 2, 3, 4, 5] }), [1, 2, 3])).toBe(2)
    expect(reuseStart(state({ absorbed: [1, 2] }), [1, 2, 3, 4])).toBe(2)
  })

  it('reuses nothing when there is nothing absorbed', () => {
    expect(reuseStart(state(), [1, 2, 3])).toBe(0)
  })

  it('tolerates a stale suffix — KV slots are idempotent and overwritten in order', () => {
    // absorbed is LONGER than the shared prefix. Slots 2..4 hold stale K/V,
    // and the delta prefill overwrites them at 2,3,4 before anything reads
    // them. This is the property the whole scheme rests on and it is exactly
    // what stops being true once pages are shared between sequences.
    expect(reuseStart(state({ absorbed: [1, 2, 3, 4, 5] }), [1, 2, 7, 8])).toBe(2)
  })
})

describe('reuseStart — hybrid, where the recurrence cannot be rewound', () => {
  const hy = (over: Partial<ReuseState> = {}) => state({ hybrid: true, ...over })

  it('reuses only when the new prompt extends EVERY absorbed token', () => {
    const s = hy({ absorbed: [1, 2, 3], gdnStatePos: 3 })
    expect(reuseStart(s, [1, 2, 3, 4, 5])).toBe(3)
  })

  it('refuses a partial match that pure attention would have accepted', () => {
    // LCP 2, absorbed 3. Attention reuses 2; hybrid must reuse 0 — the GDN
    // state already absorbed token 3 and there is no way to un-absorb it.
    const s = hy({ absorbed: [1, 2, 3], gdnStatePos: 3 })
    expect(reuseStart(s, [1, 2, 9, 9])).toBe(0)
    expect(reuseStart(state({ absorbed: [1, 2, 3] }), [1, 2, 9, 9])).toBe(2)
  })

  it('refuses when the GDN state and the KV record disagree on where they are', () => {
    // The chunked-prefill path can leave gdnStatePos behind absorbed.length.
    expect(reuseStart(hy({ absorbed: [1, 2, 3], gdnStatePos: 2 }), [1, 2, 3, 4])).toBe(0)
    expect(reuseStart(hy({ absorbed: [1, 2, 3], gdnStatePos: 4 }), [1, 2, 3, 4])).toBe(0)
  })

  it('refuses when reuse would consume the whole prompt', () => {
    // LCP === absorbed.length === 3, but len-1 is 2, so there would be no
    // token left to run. Attention clamps to 2; hybrid cannot clamp (that
    // would need a rewind) so it gives up entirely.
    const s = hy({ absorbed: [1, 2, 3], gdnStatePos: 3 })
    expect(reuseStart(s, [1, 2, 3])).toBe(0)
    expect(reuseStart(state({ absorbed: [1, 2, 3] }), [1, 2, 3])).toBe(2)
  })

  it('accepts the one-token stop overrun that normal chat produces', () => {
    // A turn ends having absorbed the stop id. The next prompt re-renders the
    // assistant turn including it, so the stop id IS the next token — the
    // reason cross-turn reuse works on Qwen3.5 at all.
    const s = hy({ absorbed: [1, 2, 3, 999], gdnStatePos: 4 })
    expect(reuseStart(s, [1, 2, 3, 999, 4, 5])).toBe(4)
  })
})

describe('reuseStart — the three ways it returns 0 regardless', () => {
  const full = { absorbed: [1, 2, 3], gdnStatePos: 3 }
  it('?reuse=0', () => expect(reuseStart(state({ ...full, prefixReuse: false }), [1, 2, 3, 4])).toBe(0))
  it('an invalidated record', () => expect(reuseStart(state({ ...full, absorbedValid: false }), [1, 2, 3, 4])).toBe(0))
  it('an empty prompt', () => expect(reuseStart(state(full), [])).toBe(0))
})

describe('noteAbsorbed', () => {
  it('appends at the end', () => {
    const s = state({ absorbed: [1, 2] })
    noteAbsorbed(s, 2, 3)
    expect(s.absorbed).toEqual([1, 2, 3])
    expect(s.absorbedValid).toBe(true)
  })

  it('TRUNCATES on a rewind — later slots are about to be overwritten', () => {
    const s = state({ absorbed: [1, 2, 3, 4, 5] })
    noteAbsorbed(s, 1, 9)
    expect(s.absorbed).toEqual([1, 9])
    expect(s.absorbedValid).toBe(true)
  })

  it('INVALIDATES on a gap, permanently', () => {
    // A position was never submitted, so the record no longer describes the
    // cache. There is no path back except resetKVTracking() — which chat.ts
    // never calls, so reuse is off for the life of that engine.
    const s = state({ absorbed: [1, 2] })
    noteAbsorbed(s, 5, 9)
    expect(s.absorbedValid).toBe(false)
    expect(s.absorbed).toEqual([1, 2])   // untouched
    noteAbsorbed(s, 2, 3)                // a later valid write does NOT heal it
    expect(s.absorbedValid).toBe(false)
  })

  it('a rewind to 0 empties the record', () => {
    const s = state({ absorbed: [1, 2, 3] })
    noteAbsorbed(s, 0, 7)
    expect(s.absorbed).toEqual([7])
  })
})

describe('the agentic turn loop, end to end', () => {
  it('reuses everything but one token on each successive turn', () => {
    // What §0.2 measured as true for real transcripts: turn N+1's prompt has
    // turn N's as an exact prefix. This is what that buys.
    const s = state()
    const turn1 = [10, 11, 12, 13]
    expect(reuseStart(s, turn1)).toBe(0)                    // cold
    turn1.forEach((id, p) => noteAbsorbed(s, p, id))
    noteAbsorbed(s, 4, 20)                                  // one token generated

    const turn2 = [...turn1, 20, 30, 31]
    expect(reuseStart(s, turn2)).toBe(5)                    // 5 of 7 reused
    turn2.forEach((id, p) => noteAbsorbed(s, p, id))
    noteAbsorbed(s, 7, 40)

    const turn3 = [...turn2, 40, 50]
    expect(reuseStart(s, turn3)).toBe(8)                    // 8 of 9
  })

  it('a branch — the agent backs up and tries a different tool call', () => {
    // Rank #2 in the plan: today the discarded branch is DESTROYED by the
    // truncation in noteAbsorbed, so exploring the second path pays full price
    // for everything after the fork. This pins that cost.
    const s = state()
    const shared = [10, 11, 12]
    shared.forEach((id, p) => noteAbsorbed(s, p, id))
    const branchA = [...shared, 20, 21]
    branchA.forEach((id, p) => noteAbsorbed(s, p, id))
    expect(s.absorbed).toEqual([10, 11, 12, 20, 21])

    // Back up to the fork and go the other way.
    const branchB = [...shared, 30, 31]
    expect(reuseStart(s, branchB)).toBe(3)                  // only the shared part
    branchB.forEach((id, p) => noteAbsorbed(s, p, id))
    expect(s.absorbed).toEqual([10, 11, 12, 30, 31])        // branch A is gone

    // Returning to A now costs the same three-token reuse, not five.
    expect(reuseStart(s, branchA)).toBe(3)
  })
})

describe('rewindSlot — replaying from a GDN snapshot when reuseStart declines', () => {
  const SLOTS = [1024, 2048, 3072, 4096]

  it('picks the NEWEST snapshot at or below the divergence', () => {
    // Prompt agrees to 3500 then changes; 4096 is past the divergence and its
    // state describes tokens this prompt no longer contains.
    expect(rewindSlot(SLOTS, 3500, 9000)).toBe(2)   // 3072
  })

  it('returns -1 when every snapshot is past the divergence', () => {
    // A different conversation sharing only a short preamble: rewinding to
    // 1024 would replay state for tokens the new prompt never had.
    expect(rewindSlot(SLOTS, 900, 9000)).toBe(-1)
  })

  it('ignores empty slots', () => {
    expect(rewindSlot([-1, -1, -1, -1], 5000, 9000)).toBe(-1)
    expect(rewindSlot([-1, 2048, -1, -1], 5000, 9000)).toBe(1)
  })

  it('leaves at least one token to run on an IDENTICAL prompt', () => {
    // The retry case: the client resent a prompt the cache already holds in
    // full, so lcp === promptLen. reuseStart refuses this outright. A snapshot
    // at promptLen - 1 is legal and replays exactly one token — enough to
    // produce the logits prefill's last step is responsible for.
    expect(rewindSlot([4095], 4096, 4096)).toBe(0)
    // ...but one AT promptLen is not: it would leave nothing to compute with.
    expect(rewindSlot([4096], 4096, 4096)).toBe(-1)
  })

  it('never rewinds to position 0 — that is a full re-prefill, not a rewind', () => {
    expect(rewindSlot([0], 5000, 9000)).toBe(-1)
  })

  it('prefers a later snapshot even when an earlier one also qualifies', () => {
    expect(rewindSlot([4096, 1024], 5000, 9000)).toBe(0)
    expect(rewindSlot([1024, 4096], 5000, 9000)).toBe(1)
  })
})

describe('dropSnapshotsAbove — a rewind invalidates every snapshot above it', () => {
  it('voids the doomed ones and keeps the prefix ones', () => {
    const ring = [1024, 2048, 3072, 4096]
    dropSnapshotsAbove(ring, 2048)
    expect(ring).toEqual([1024, 2048, -1, -1])
  })

  it('keeps a snapshot exactly AT the rewind point', () => {
    // The prompt agreed with the record down to there, so the prefix that slot
    // encodes is unchanged — it is the best rewind point, not a stale one.
    const ring = [2048]
    dropSnapshotsAbove(ring, 2048)
    expect(ring).toEqual([2048])
  })

  it('leaves empty slots alone', () => {
    const ring = [-1, 4096, -1]
    dropSnapshotsAbove(ring, 1024)
    expect(ring).toEqual([-1, -1, -1])
  })

  it('stops a NON-MONOTONIC rewind pair from restoring a dead conversation', () => {
    // The failure an adversarial simulation found in 2,929 of 20,000 randomized
    // conversations, reduced to its shape. A client that rewrites the SAME
    // trailing block every turn produces increasing rewind points and never
    // reaches it, which is why six live rewinding turns looked clean.
    const ring = [646, -1, -1, -1]

    // turn 6 diverges at 747, rewinds to 646, replays, snapshots at 1254
    let slot = rewindSlot(ring, 747, 1255)
    expect(ring[slot]).toBe(646)
    dropSnapshotsAbove(ring, 646)
    ring[1] = 1254

    // turn 7 diverges at 1245 — BELOW 1254 — and rewinds to 646 again. Slot 1
    // now describes turn 6's tokens, which this replay is about to overwrite.
    slot = rewindSlot(ring, 1245, 1363)
    expect(ring[slot]).toBe(646)
    dropSnapshotsAbove(ring, 646)
    expect(ring[1]).toBe(-1)      // without this, turn 8 restores turn 6's state
    ring[2] = 1362

    // turn 8 agrees to 1308. The only legal point is 646, not the dead 1254.
    slot = rewindSlot(ring, 1308, 1732)
    expect(ring[slot]).toBe(646)
  })
})

// ── the rewind point a turn actually needs ──────────────────────────────────
//
// Hand-derived from the two facts the engine states about itself, not from
// running it:
//   1. buildChatPrompt reports `genStart`, the index where the trailing
//      generation prompt begins. The NEXT turn re-renders this turn's reply in
//      its place, so genStart is exactly where the two token sequences diverge:
//      LCP == genStart.
//   2. saveGdnCkpt's argument is a COUNT of absorbed tokens.
//
// This exists because both halves were got wrong on 2026-08-19 and neither was
// visible: snapshots on the CHUNK_CAP grid land above the divergence (so reuse
// silently falls to 0), and a snapshot labelled one short restores a state that
// has absorbed one token too many (so the recurrence replays a token — fluent
// wrong output, and a gate asserting `reused > 0` reports success).
describe('the generation-prompt rewind point', () => {
  // A conversation whose prompt is 500 tokens, with the generation prompt
  // occupying the last 9 — so genStart is 491 and the next turn's LCP is 491.
  const PROMPT = 500
  const GEN_START = 491

  it('a CHUNK_CAP grid alone never produces a usable slot for a short prompt', () => {
    // One chunk covers the whole prompt, so the only boundary is at its end.
    const ring = [PROMPT - 1, -1, -1, -1]
    expect(rewindSlot(ring, GEN_START, PROMPT)).toBe(-1)
  })

  it('a snapshot AT the generation-prompt boundary is selected', () => {
    const ring = [GEN_START, -1, -1, -1]
    expect(rewindSlot(ring, GEN_START, PROMPT)).toBe(0)
  })

  it('and it is preferred over an earlier chunk boundary', () => {
    // Both are usable; the higher one replays fewer tokens.
    const ring = [256, GEN_START, -1, -1]
    expect(rewindSlot(ring, GEN_START, PROMPT)).toBe(1)
  })

  it('a snapshot one PAST the boundary is refused, not silently used', () => {
    // This is what a mislabelled snapshot looks like from rewindSlot's side
    // when the label is too HIGH: correctly rejected.
    expect(rewindSlot([GEN_START + 1, -1, -1, -1], GEN_START, PROMPT)).toBe(-1)
  })

  it('a snapshot labelled one SHORT is accepted — which is why the label matters', () => {
    // rewindSlot cannot tell a correct label from one that is too LOW: both are
    // <= the limit. It returns the slot, the caller sets gdnStatePos to the
    // label and replays from there, and the state has already absorbed that
    // token. Nothing downstream catches it, so the +1 belongs at the call site.
    expect(rewindSlot([GEN_START - 1, -1, -1, -1], GEN_START, PROMPT)).toBe(0)
  })

  it('the boundary is below promptLen-1, so the limit never clips it', () => {
    // A generation prompt is always at least one token, so genStart < len-1 and
    // rewindSlot's own min(lcp, len-1) clamp is not what decides this case.
    expect(GEN_START).toBeLessThan(PROMPT - 1)
  })
})
