// YARN ROPE — our inv_freq table against DeepSeek's own.
//
// The fixture is generated by scripts/yarn-ref.py, which EXECUTES the yarn
// helpers out of the checkpoint's shipped modeling_deepseek.py rather than
// reimplementing them. That distinction is the whole value of this test: a
// reimplementation checked against our own reading of the paper would prove
// only that we are self-consistent, and yarn's failure mode is a table that
// looks entirely reasonable and quietly ruins long context.

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { makeModelSpec, mlxParamNaming, ropeAttnScale, ropeInvFreqTable } from '../../src/compiler/model-spec.ts'

const ref = JSON.parse(readFileSync(join(import.meta.dirname, '../fixtures/yarn-ref.json'), 'utf8')) as {
  dim: number; base: number; factor: number; betaFast: number; betaSlow: number
  originalMaxPositionEmbeddings: number; mscale: number; mscaleAllDim: number
  correctionRange: [number, number]; attnScale: number; invFreq: number[]
}

/** A spec whose ROTARY dims are DeepSeek-V2-Lite's. Everything else is filler
 *  chosen only to satisfy makeModelSpec — the table depends on rotaryDim,
 *  ropeTheta and ropeScaling, nothing else. */
const specWith = (scaling: Parameters<typeof makeModelSpec>[0]['ropeScaling']) => makeModelSpec({
  id: 'yarn-fixture', d: 2048, layers: 1, heads: 16, kvHeads: 16,
  headDim: ref.dim, ffn: 2048, vocab: 128, pageSize: 16, maxPages: 4, maxSeq: 4096,
  ropeTheta: ref.base, rmsEps: 1e-6, tiedEmbeddings: false, qkNorm: false,
  stops: [0], chatTemplateId: 'chatml', tokenizerKind: 'byteLevel',
  hfRepo: 'none', ropeScaling: scaling, paramNaming: mlxParamNaming(''),
})

const YARN = specWith({
  ropeType: 'yarn', factor: ref.factor, betaFast: ref.betaFast, betaSlow: ref.betaSlow,
  originalMaxPositionEmbeddings: ref.originalMaxPositionEmbeddings,
  mscale: ref.mscale, mscaleAllDim: ref.mscaleAllDim,
})

describe('yarn rope', () => {
  it('reproduces DeepSeek\'s inv_freq table', () => {
    const got = ropeInvFreqTable(YARN)
    expect(got.length).toBe(ref.invFreq.length)
    let worst = 0
    for (let i = 0; i < got.length; i++) {
      worst = Math.max(worst, Math.abs(got[i] - ref.invFreq[i]) / ref.invFreq[i])
    }
    // f32 storage against the vendor's f32 — anything above rounding is a
    // different table, not a rounding difference.
    expect(worst).toBeLessThan(1e-6)
  })

  it('keeps the low band unstretched and divides the high band by the factor', () => {
    const got = ropeInvFreqTable(YARN)
    const plain = ropeInvFreqTable(specWith(undefined))
    const [low, high] = ref.correctionRange
    // Below `low` yarn leaves the frequency alone; above `high` it is fully
    // interpolated. The ramp between them is what the fixture pins exactly.
    // Compared RELATIVELY: the table is a Float32Array and these frequencies
    // reach 3e-5, where an absolute bound is really a test of f32's mantissa.
    const near = (a: number, b: number) => expect(Math.abs(a - b) / Math.abs(b)).toBeLessThan(1e-6)
    near(got[0], plain[0])
    near(got[low], plain[low])
    near(got[high], plain[high] / ref.factor)
    near(got[got.length - 1], plain[plain.length - 1] / ref.factor)
  })

  it('carries the logit scale yarn applies outside the table', () => {
    // mscale^2, applied to attention logits — not to the frequencies. Folding
    // it into the table instead would be wrong at every position.
    expect(ropeAttnScale(YARN)).toBeCloseTo(ref.attnScale, 10)
    expect(ropeAttnScale(specWith(undefined))).toBe(1)
  })

  it('leaves llama3 scaling and the unscaled table alone', () => {
    const llama3 = specWith({
      ropeType: 'llama3', factor: 32, lowFreqFactor: 1, highFreqFactor: 4,
      originalMaxPositionEmbeddings: 8192,
    })
    expect(ropeAttnScale(llama3)).toBe(1)
    // A llama3 spec must not accidentally take the yarn branch.
    expect(Array.from(ropeInvFreqTable(llama3))).not.toEqual(Array.from(ropeInvFreqTable(YARN)))
  })
})
